import type {
  PreparedScreening,
  ScreeningCatalog,
  ScreeningConfig,
  ScreeningMode,
  ScreeningPreview,
} from "./screening-contract";
import {
  artifactBase,
  getChatState,
  saveArtifact,
  updateChatState,
} from "./chat-store";
import { sessionStore } from "./session-store";
import {
  uploadEnrichmentFiles,
} from "./tool-client";

type Trace = {
  tool: string;
  args: unknown;
  result?: unknown;
  error?: string;
  startedAt: string;
  finishedAt: string;
  status: "success" | "error";
};
function recordCalls(sessionId: string, calls: Trace[]) {
  for (const call of calls)
    sessionStore.addEvent({
      sessionId,
      kind: "tool",
      origin: "workspace",
      status: call.status,
      title:
        call.tool === "get_candidate_source_data"
          ? "Read selected company sources"
          : call.tool === "save_checkpoint"
            ? "Save setup snapshot"
            : call.tool.replaceAll("_", " "),
      toolName: call.tool,
      args: call.args,
      result: call.result,
      error: call.error,
      startedAt: call.startedAt,
      finishedAt: call.finishedAt,
      durationMs: Math.max(
        0,
        Date.parse(call.finishedAt) - Date.parse(call.startedAt),
      ),
    });
}
async function request<T>(
  sessionId: string,
  route: string,
  input: unknown,
): Promise<T> {
  const response = await fetch(`/api/screening/${route}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(input),
  });
  const body = await response.json();
  recordCalls(sessionId, Array.isArray(body.calls) ? body.calls : []);
  if (!response.ok)
    throw new Error(body.error ?? "The setup could not be prepared.");
  return body as T;
}
export async function getScreeningCatalog(
  sessionId: string,
  runId?: string,
): Promise<ScreeningCatalog> {
  return (
    await request<{ catalog: ScreeningCatalog }>(sessionId, "catalog", {
      runId,
    })
  ).catalog;
}
export async function previewScreening(
  sessionId: string,
  runId: string | undefined,
  config: ScreeningConfig,
): Promise<ScreeningPreview> {
  return (
    await request<{ preview: ScreeningPreview }>(sessionId, "preview", {
      runId,
      config,
    })
  ).preview;
}
export async function approveScreening(
  sessionId: string,
  runId: string | undefined,
  config: ScreeningConfig,
  preview: ScreeningPreview,
): Promise<PreparedScreening> {
  const { prepared } = await request<{ prepared: PreparedScreening }>(
    sessionId,
    "approve",
    { runId, config, fingerprint: preview.fingerprint, approved: true },
  );
  const existing = getChatState(sessionId).artifacts.find(
    (a) =>
      a.type === "screening-setup" &&
      a.prepared.fingerprint === prepared.fingerprint,
  );
  if (existing) return prepared;
  const artifact = saveArtifact(sessionId, {
    ...artifactBase(prepared.title),
    type: "screening-setup",
    prepared,
  });
  const messageId = crypto.randomUUID();
  updateChatState(sessionId, (state) => ({
    ...state,
    branchMessageIds: [...state.branchMessageIds, messageId],
  }));
  sessionStore.addEvent({
    sessionId,
    kind: "approval",
    origin: "workspace",
    status: "success",
    title: "Setup approved and saved",
    result: {
      setupId: prepared.id,
      fingerprint: prepared.fingerprint,
      provider: prepared.provider,
      mode: prepared.mode,
      executed: false,
      checkpoint: prepared.checkpoint,
    },
  });
  sessionStore.addEvent({
    sessionId,
    messageId,
    kind: "message",
    role: "assistant",
    origin: "workspace",
    status: "success",
    title: "Setup saved",
    text: "The setup and input snapshot are saved. Background screening shows provider status and progress.",
    content: [
      {
        type: "text",
        text: "The setup and input snapshot are saved. Background screening shows provider status and progress.",
      },
      {
        type: "data",
        name: "screening-artifact",
        data: { artifactId: artifact.id },
      },
    ],
  });
  return prepared;
}
export async function hydrateScreeningSources(sessionId: string, runId: string, files: File[]): Promise<void> {
  await uploadEnrichmentFiles(files, runId, { sessionId });
}

export type ScreeningPromptInput = {
  sessionId?: string;
  mode: ScreeningMode;
  definition: string;
  goodFits: string[];
  badFits: string[];
  deferred: string[];
  inputColumns: string[];
  outputColumns: string[];
  request: string;
};
export type ScreeningPromptResult = { prompt: string; promptId: string; promptVersion: number; promptHash?: string };
/** Examples are saved as free text, one example per line. */
export function splitExamples(text?: string): string[] {
  return (text ?? "")
    .split(/\r?\n/)
    .map((line) => line.trim().replace(/^[-*•]\s+/, ""))
    .filter(Boolean);
}
/** The screening or question prompt, generated by the bridge from the prompt files. */
export async function fetchScreeningPrompt(
  input: ScreeningPromptInput,
  signal?: AbortSignal,
): Promise<ScreeningPromptResult> {
  const response = await fetch("/api/prompts/screening-draft", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(input),
    signal,
  });
  const body = await response.json().catch(() => ({}));
  if (!response.ok || typeof body.prompt !== "string")
    throw new Error(body.error ?? "The prompt could not be generated.");
  return body as ScreeningPromptResult;
}
